<a href="https://colab.research.google.com/github/vedantpople4/ML_Projects/blob/master/ANN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [5]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [8]:
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values
print(x)
print("\n")
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


[1 0 1 ... 1 1 0]


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
print(x)

[[ 0.57873591 -0.57873591  0.99720391 ...  0.64609167  0.97024255
   0.02188649]
 [ 0.57873591 -0.57873591 -1.00280393 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.57873591 -0.57873591  0.99720391 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.57873591 -0.57873591  0.99720391 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.72790383  1.72790383 -1.00280393 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.57873591 -0.57873591  0.99720391 ...  0.64609167 -1.03067011
  -1.07636976]]


In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)


In [19]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [20]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6584 - accuracy: 0.6299
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4761 - accuracy: 0.7945
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4502 - accuracy: 0.7981
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4336 - accuracy: 0.8041
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4167 - accuracy: 0.8108
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3989 - accuracy: 0.8223
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3848 - accuracy: 0.8322
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3762 - accuracy: 0.8384
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3706 - accuracy: 0.8415
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3668 - accura

In [21]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1504   91]
 [ 190  215]]
